sync:
  - name: environment
    source: ./files/zshenv.zsh
    target: ~/.zshenv
  - name: interactive
    source: ./files/zshrc.zsh
    target: ~/.config/zsh/.zshrc
  - name: keys
    source: ./files/keys.zsh
    target: ~/.config/zsh/keys.zsh
  - name: tools
    source: ./files/tools.zsh
    target: ~/.config/zsh/tools.zsh
  - name: fzf
    source: ./files/fzf.zsh
    target: ~/.config/zsh/fzf.zsh
