// Generates deterministic static shell completions from the CLI and catalog contracts.

import { spawnSync } from 'node:child_process';
import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';

import { cliContract } from '../../src/commands.js';
import type { CatalogManifest } from '../../src/schema.js';

export function generateZshCompletion(manifest: CatalogManifest): string {
  const commands = cliContract.commands
    .map(
      ({ name, description }) => `    ${quoteForZsh(`${name}:${escapeDescription(description)}`)}`,
    )
    .join('\n');
  const themes = manifest.themes.map((themeId) => `    ${quoteForZsh(themeId)}`).join('\n');
  const helpOptions = cliContract.helpFlags
    .map((flag) => `    ${quoteForZsh(`${flag}:Show help.`)}`)
    .join('\n');
  const commandOptions = Object.fromEntries(
    cliContract.commands.map((command) => [
      command.name,
      [
        ...cliContract.helpFlags.map((flag) => ({ name: flag, description: 'Show help.' })),
        ...command.options,
      ]
        .map(
          ({ name, description }) =>
            `    ${quoteForZsh(`${name}:${escapeDescription(description)}`)}`,
        )
        .join('\n'),
    ]),
  ) as Record<(typeof cliContract.commands)[number]['name'], string>;

  return `#compdef ${cliContract.name}

# Generated by Forge. Rebuild @forge/swatch instead of editing this file.
_${cliContract.name}() {
  local context state state_descr line
  typeset -A opt_args
  local -a commands current_options help_options list_options themes

  commands=(
${commands}
  )
  themes=(
${themes}
  )
  help_options=(
${helpOptions}
  )
  list_options=(
${commandOptions.list}
  )
  current_options=(
${commandOptions.current}
  )

  _arguments -C \\
    '(-h --help)'{-h,--help}'[Show help.]' \\
    '1:command:->command' \\
    '*::argument:->argument'

  case $state in
    command)
      _describe 'command' commands
      ;;
    argument)
      case $words[1] in
        list)
          _describe 'option' list_options
          ;;
        get)
          _describe 'option' help_options
          _describe 'theme ID' themes
          ;;
        current)
          _describe 'option' current_options
          ;;
        use)
          _describe 'option' help_options
          _describe 'theme ID' themes
          ;;
      esac
      ;;
  esac
}

_${cliContract.name} "$@"
`;
}

export async function writeZshCompletion(
  destination: string,
  manifest: CatalogManifest,
): Promise<void> {
  await mkdir(path.dirname(destination), { recursive: true });
  await writeFile(destination, generateZshCompletion(manifest));

  const result = spawnSync('zsh', ['-n', destination], { encoding: 'utf8' });
  if (result.error) throw result.error;
  if (result.status !== 0) {
    throw new Error(`Zsh completion validation failed: ${result.stderr.trim()}`);
  }
}

function escapeDescription(description: string): string {
  return description.replaceAll(':', '\\:');
}

function quoteForZsh(input: string): string {
  return `'${input.replaceAll("'", "'\\''")}'`;
}
