import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";

import { expandHome } from "../lib/paths.js";

// The marker is the ownership proof for generated files: writeGeneratedFile
// refuses to overwrite any target that does not contain it. Never bypass.
export const GENERATED_MARKER = "Generated by Forge";

export interface Builder {
  build(task: { source: string; output: string; opts: unknown }): Promise<void>;
}

export async function writeGeneratedFile(
  label: string,
  output: string,
  content: string,
) {
  const target = expandHome(output);
  let existing: string | null = null;

  try {
    existing = await readFile(target, "utf8");
  } catch (error) {
    if (
      !(
        error &&
        typeof error === "object" &&
        "code" in error &&
        error.code === "ENOENT"
      )
    ) {
      throw error;
    }
  }

  if (existing !== null) {
    if (!existing.includes(GENERATED_MARKER)) {
      throw new Error(
        `[conflict] ${label}: ${target} exists and is not generated by Forge; back it up or remove it manually`,
      );
    }

    if (existing === content) {
      console.log(`[skip] ${label}: unchanged`);
      return;
    }
  }

  await mkdir(path.dirname(target), { recursive: true });
  await writeFile(target, content, "utf8");
  console.log(`[build] ${label}: ${target}`);
}
